### ISSUE TITLE
Missing Swing PLAF classes in java

### ISSUE THREAD

**Issue by miquelmassot** [LSTS/neptus#106]
When running `ant` to build neptus on a Ubuntu 18.04 machine, there are a bunch of errors which I list below:

    neptus/src/pt/lsts/neptus/gui/system/selection/MainSystemSelectionCombo.java:51: error: package com.sun.java.swing.plaf.windows does not exist
    neptus/src/pt/lsts/neptus/console/plugins/PluginManager.java:64: error: package com.sun.java.swing.plaf.windows does not exist
    cannot find symbol     [javac] import javax.annotation.Generated;

as well as a couple of classes under javax: WebEndpoint, SOAPBinding, WebMethod, WebResult...

Am I missing something? I was following your wiki at https://github.com/LSTS/neptus/wiki/Compiling

**Comment by miquelmassot** [comment]
OK found that it works with Java 8.
To change java versions in Ubuntu I had to run `sudo update-alternatives --config java` and select a non-default (older) version of java. Worth mentioning in the installation guide.

**Comment by paulosousadias** [comment]
If you check the Java requirements is Java 8: https://github.com/LSTS/neptus/wiki/Requirements.
