### ISSUE TITLE
MRA: Log marks at LogTableVisualization

### ISSUE THREAD

**Issue by tsmarques** [LSTS/neptus#113]
Hi,

I've found two issues when adding marks at LogTableVisualization:

1 - The marks are tied to the [table row](https://github.com/LSTS/neptus/blob/67e54cf4b7b3d53e775bac436f5068a1faee9b25/src/pt/lsts/neptus/util/llf/LogTableVisualization.java#L187). This means that when I change the sorting of the table the mark stays at the same row even if the data entry changed.

![neptus_mark](https://user-images.githubusercontent.com/4097824/67637218-16becd80-f8d0-11e9-8887-2f0f16e31d01.png)

After sorting

![neptus_mark_2](https://user-images.githubusercontent.com/4097824/67637221-20e0cc00-f8d0-11e9-858b-eeb4d53a24fb.png)

2 - [This](https://github.com/LSTS/neptus/blob/67e54cf4b7b3d53e775bac436f5068a1faee9b25/src/pt/lsts/neptus/util/llf/LogTableVisualization.java#L353) loop bound is wrong (Seems that the -1 shouldn't be there). The behavior is:

- If the timestamp between the last and second to last is less than 500ms the the mark is added to the second to last entry, instead of the last
- Otherwise [the entry is ignored and the mark is not added](https://github.com/LSTS/neptus/blob/67e54cf4b7b3d53e775bac436f5068a1faee9b25/src/pt/lsts/neptus/util/llf/LogTableVisualization.java#L355)

**Comment by paulosousadias** [comment]
Viva Tiago,
  Podes re-testar p.f?
Ab,
Paulo

Tiago Sá Marques <notifications@github.com> escreveu no dia domingo,
27/10/2019 à(s) 15:47:
