### ISSUE TITLE
Feature request: Naming real-time plots

### ISSUE THREAD

**Issue by krisgry** [LSTS/neptus#114]
I tend to add lots of real-time plots to the console. For example: I'll first tune the lateral dynamics, which needs some plots, and then I'll continue with the longitudinal dynamics, requiring a new set of plots. I then might want to look at some of the lateral plots, to see that they still make sense. But; in the mess of ~10 real-time plots I've added to the console, it is difficult to find/remember which plot I'm looking. 

All Real-time plots are all labeled "Real-Time plot" in the "View"-menu.

Would it be possible to have them show a unique, preferably user specified, name? A "simple" solution would be to name it "Real-Time plot: <name>", where <name> is the name of the first variable to be plotted, as specified in the traces script (e.g. "height: ${EstimatedState.height};" would result in "Real-Time plot: height".

**Comment by kmolima** [comment]
Thank for the suggestion, but unfortunately, this specific feature is not feasible to implement due to the Neptus Plugin design. Nevertheless, we implemented an alternative, indexing the duplicated plugins by order of addition. This feature is available in:
https://github.com/LSTS/neptus/pull/116
