### ISSUE TITLE
Error building the repository

### ISSUE THREAD

**Issue by TheAlchemist4AI** [LSTS/neptus#129]
Hello all
I am trying to build the repo with following tools

IntelliJ version: 2022.1.4 Community Edition
Gradle version: 7.5
Java version:  18.0.1
OS: Window 11 64 Bit

The repo is building successfully but when i try to execute it is throwing the error below
![build-error](https://user-images.githubusercontent.com/109099821/180588612-e405f892-81ad-48fe-b601-91c73a5b04c7.jpg)

Any help to resolve the issue ?

Am I using the right version of the tools.

Regards

**Comment by TheAlchemist4AI** [comment]
The problem resolved now.
Issue was with JDK and JRE versions.
Thanks

**Comment by paulosousadias** [comment]
Yes, Java 11 is the target JDK to use. The requirements are here: https://github.com/LSTS/neptus/wiki/Requirements
