### ISSUE TITLE
Run a simulation without vehicle

### ISSUE THREAD

**Issue by serguica** [LSTS/neptus#52]
Hi! I'm new working with Neptus, the environment is ready. I can build with ant like are specified in the wiki and run Neptus. How can I make a simulation without physical vehicle?

Thanks!

**Comment by paulosousadias** [comment]
Hi Serguica,

  Neptus is part of a toolchain for autonomous vehicles. The easiest way is
to use a DUNE (onboard software) in a simulation profile.
  Check http://www.lsts.pt/toolchain and DUNE at
https://github.com/LSTS/dune/wiki. Once you've compile it you can run, for
example, the lauv-noptilus-1 simulated vehicle with the command "./dune -c
lauv-noptilus-1 -p Simulation". Then you will see it on Neptus.
  By the way can you provide a bit of information of what you are doing
with these tools, and where are you from?

Regards,
Paulo Dias

2016-02-19 14:22 GMT+00:00 serguica <notifications@github.com>:

**Comment by serguica** [comment]
Sorry for the delay, I tried what you say and it works!

I'm a student of the UPV of Valencia, working with Javier and Jose Vicente Busquets in a project.

Regards,
Sergio
