### ISSUE TITLE
Non-functioning Height/Depth input field in Location Editor

### ISSUE THREAD

**Issue by krisgry** [LSTS/neptus#88]
Hi,
I believe @jffortuna has reported this to you internally, but I'll do it again to have a public record of it.

In the Location Editor (In plan editor, select (e.g.) a goto, click the three dots in the "Location"-field), there is an input field where Height/Depth can be input. However this has no effect on "Z" of the goto, which is confusing.

![image](https://user-images.githubusercontent.com/1384876/38431096-702d0544-39c3-11e8-9bc5-7b40fb659d5a.png)

**Comment by zepinto** [comment]
There is a fix for this in lsts/neptus@9b2a522
