### ISSUE TITLE
Add section on plotting in Neptus (and possibly make the wiki editable)

### ISSUE THREAD

**Issue by krisgry** [LSTS/neptus#92]
Hi,
To make it easier for everyone (particularly new PhD and master students), I have written a short tutorial on how to plot in Neptus. Great if you can include it!

Also, I noticed that the Neptus wiki is not editable (like the DUNE wiki is), so to make contributions like this easier in the future, you could consider making it editable.

Here is my suggested tutorial. Feel free to make changes. Would also be great if you could add some information on what is required for DUNE and Neptus to communicate (ref my **TODO**):
### Neptus plotting tutorial
Neptus has the capability to plot IMC messages, using the _Real-Time plot_ (found in _Viev_) 
In the [DUNE _Task Interactions_ tutorial][https://github.com/LSTS/dune/wiki/Task-Interactions], we displayed the temperature by printing it to the command line. This way of displaying values is only appropriate for debugging purposes, as it is difficult to follow multiple values, and it is difficult to spot changes and trends. Instead, we will use the plotting capabilities of neptus to display the values. This will also show how you can modify DUNE config parameters from Neptus, in real time.

*	Edit the `prodcon.ini` config file from the _Task Interactions_ tutorial. To interact with Neptus, DUNE needs to run `Transports.Announce` and `Transports.Discovery` (**TODO**: is that all?). For simplicity, we will pretend that we are a simulated UAV, and add `[Require ../../simulation/uav.ini]` to the start of `prodcon.ini`, since configuration already takes care of Neptus interactions. `prodcon.ini` should now look like this:
```
[Require ../../simulation/uav.ini]

[Tutorials.TempProd/P1]
Enabled = Always
Entity Label = Producer1
Mean value = 37
Standard deviation = 0.5

[Tutorials.TempProd/P2]
Enabled = Always
Entity Label = Producer2
Mean value = 45
Standard deviation = 0.1

[Tutorials.TempCons]
Enabled = Always
Entity Label = Consumer
Target Producer = Producer1

[Transports.Logging]
Enabled = Always
Entity Label = Logger
Transports = Temperature
```
*	Generate configuration file for neptus: Neptus needs to know what parameters are available from a given vehicle, so we need to generate this file and place it in the appropriate folder: `./dune -c development/Tutorials/prodcon -p Simulation -X /path/to/neptus/conf/params`.
*	Run dune: `./dune -c development/Tutorials/prodcon -p Simulation -X /path/to/neptus/conf/params` and open your desired Neptus console.
*	Watch the IMC messages in Neptus: In _View_->_Incomming data_, you should select *x8-00* in the dropdown at the top. Find _Temperature_ in the list on the left. The tabs indicate the different entities that send the _Temperature_ message, so you should see both _Producer1_ and _Producer2_.
*	Display values in real time plot:
    *	Open _View_->_Real-Time plot_, click _Settings_, change the text field to say `temperature: ${Temperature.value}`, and hit the cross.
    *	What happens? The value will jump between the values from the two producers, which is not ideal
    *	Instead, change the _Settings_ text field to 
        ```
        temperature_p1: ${Temperature.Producer1.value}; 
        temperature_p2: ${Temperature.Producer2.value};
        ```
        Ahh, much better: now each of the two producers have their own line in the plot.
*	To illustrate a point, we will adjust the temperature from the two tasks, by adjusting 
    *	Open _System configuration_ for the *x8-00*, and check _Access developer parameters_. A list of Tasks, and their corresponding parameters, should appear.
    *	Change _Mean value_ under Producer1 to 0.1 and Temperature under Producer2 to 100. Click _Send_
    *	What happens in the plot? It would be difficult to spot small changes in the temperatures, since the range of the two temperatures differ. 
    * To see the dynamics of both signals, we will move _temperature\_p2_ to its own plot:
        * Open _View_->_Plugin Manager_, select _Real-Time plot_ in the list on the left, and click _Add_. Another _Real-Time plot_ item should appear in the _View_-menu. Move `temperature_p2: ${Temperature.Producer2.value};` to the _Settings_ text field of this new plot.
* Basic math operations: If you want to display the temperature from Producer 2 to be displayed in Fahrenheit instead, you could change the text field to `temperature_p2: ${Temperature.Producer2.value}*1.8 + 32;` This is perhaps more useful when converting radians to degrees: `pitch: ${EstimatedState.theta}*180/Math.PI`

**Comment by krisgry** [comment]
I updated the section to reflect the changes in the DUNE tutorial (now the temperature has a random component, making it more interesting to plot)

**Comment by paulosousadias** [comment]
Hi Kristoffer,

  I think I matched the settings as dune. Can you try to edit? And thanks
for the contribution.

Regards,
Paulo

Jose Pinto <notifications@github.com> escreveu no dia segunda, 30/07/2018
à(s) 10:18:

**Comment by krisgry** [comment]
Thanks! Added it now, so consider this issue done.
