### ISSUE TITLE
Feature suggestion: Store realtimeplot scripts

### ISSUE THREAD

**Issue by krisklau** [LSTS/neptus#93]
Would be nice to be able to select beetween previously stored (named!) realtimeplot scripts with a dropdown menu. The different scripts could be saved with the console. 

E.g., I might have two "things" I want to plot:
 1. HeadingDebug: CurrentHeading, DesiredHeading
 2. AltitudeDebug: CurrentAltitude, DesiredAltitude

Instead of comment in/out these parts in the script (can't plot both as they have very different ranges), I could then save them and select them with a drop-down menu.

**Comment by zepinto** [comment]
Would it be ok to have a folder in (under conf/) where these different scripts would be loaded from?
In this case there would be a **HeadingDebug.plot** and **AltitudeDebug.plot** files that could be selected to replace the contents of the real-time plot code editor.

**Comment by paulosousadias** [comment]
Changes done on branch feature/realtimeplot-groovy

**Comment by kmolima** [comment]
The changes on the real-time plot in Neptus are available on the branch: [feature/realtimeplot-groovy](https://github.com/LSTS/neptus/tree/feature/realtimeplot-groovy)
Commit: 4da4c5ff2309355df58cd031f885de02483901da
 Now the plot can have different and configurable XY series, including the previously used timeseries. 
There is also a tutorial video of the usage of the plugin:
[link to drive](https://drive.google.com/file/d/1XuowHPh1EYdBHkPW_iZEG0a8bHPVQKQP/view?usp=sharing
) The rate parameter disappeared in this version and it is fixed on 1000 miliseconds. If you find it is necessary we can work on that.
The MRA plots are also being migrated to groovy

**Comment by krisgry** [comment]
For tuning controllers/estimators, which is a major part of what we spend time on in the field, it is necessary with a higher update rate than 1000 ms. In the old realtime plot, I usually set this to 100 ms.
