### ISSUE TITLE
Real-time plot; documentation and debug output

### ISSUE THREAD

**Issue by krisgry** [LSTS/neptus#94]
It would be very beneficial to have some more information on what is possible in the real-time plot. We only recently discovered that the "language" in the real-time plot is Javascript, so it would be nice to write that either as a comment in the real-time plot settings menu itself, or perhaps as an addition to the [plotting tutorial](https://github.com/LSTS/neptus/wiki/Plotting-tutorial)

Slightly related; It would also be valuable for the user to see some (debug) output of the parsing of the "plot specification". For complex expressions, it can be difficult to figure out what caused the plot to stop working.

(Both of these issues are on a "nice to have" level.)

**Comment by krisgry** [comment]
I added a short section on JavaScript in the plotting tutorial now

**Comment by krisgry** [comment]
A related question; is it possible to filter on vehicle, in a similar manner as filtering on entities, in the real time plot? Something like this: To only plot the height reference of the x8-02 from the YoloHeight entity; height: ${Reference.x8-02.YoloHeight.z.value}

**Comment by paulosousadias** [comment]
Big changes on this on branch feature/realtimeplot-groovy
