### ISSUE TITLE
Plan configurations are (still) changed by Neptus

### ISSUE THREAD

**Issue by krisgry** [LSTS/neptus#95]
I have reported this bug before, and it was reportedly fixed, but now we are having the same problems all over. 

**The problem**
We use maneuver-scope parameters to choose different controller-specific parameters (e.g. what controllers should be active for a given maneuver. On a side note; we are open for suggestions on how to improve this :)) The pitcure shows some of these parameters from a GoTo in a typical scenario:
![image](https://user-images.githubusercontent.com/1384876/48371902-4673c600-e6bd-11e8-8ef6-ab7a1fbf5b76.png)

As an example; to use the ardupilot guidance controllers, the AP tracker parameter is selected, whereas "Use controller" of "Bank to turn...", "Height Glideslope...." and "FBWA Longitudinal..." is set to true to let DUNE handle the guidance (and send roll/pitch/throttle to AP). We set this for the entire plan by using the "Payload settings" menu. This works fine for the most part, but every now and then when we double check the plan before sending it to the vehicle (a routine we have established because of this problem) some of the parameters have changed. For example, we had a crash where one of the GoTos had changed from using DUNE guidance to using AP.

The problem is very difficult to reproduce, at least in simulation. However; when we went flying last week it seemingly happened all the time. It seems very strange, but could it be related to the communication link?

[Here is a zip of the log folder in neptus](https://www.dropbox.com/s/q26qwjs3sv7p6a8/neptus_log.zip?dl=0) The dates in question are Nov 5th-7th. I also have DUNE logs, and the entire neptus folder, if any of that is of interest.

Appreciate any input and help on investigating this bug!

**Comment by paulosousadias** [comment]
Can you check which git hash you are in regarding LSTS code (the hash you
have is not on our git)?
best

Kristoffer Gryte <notifications@github.com> escreveu no dia segunda,
12/11/2018 à(s) 20:17:

**Comment by krisgry** [comment]
Thanks for looking into this. We are currently based on 3ac05f69b2cba2938f077e9632647c185366f02b

**Comment by paulosousadias** [comment]
The hash you've sent is not valid in here. You can check in your code if your branch contains the hash e58d394d or in alternative if the imcjava on your branch contains the hash 22c899cb.
If not you must merge the develop branch.

**Comment by krisgry** [comment]
Sorry for being so useless... The latest hash is https://github.com/LSTS/neptus/commit/e3baadbcfb7b33c6e9cbf2ec92eac71737b66e7d
However, we do have the "22c899c Added option to type clone a message" commit in our imcjava, which has been used to re-generate libimc for neptus.

**Comment by paulosousadias** [comment]
No able to reproduce it with this fix, bu please try.
https://github.com/LSTS/neptus/tree/feature/manpayloadlost

**Comment by krisgry** [comment]
Closing this. Will re-open if we see this again. Thanks :)

**Comment by krisgry** [comment]
@paulosousadias I noticed that the feature branch you referred to has _not_ been merged into develop. Is there a reason for this? Are you using this, or did you find a better way to solve the problem? 
Thanks,
Kristoffer

**Comment by krisgry** [comment]
Thanks for the swift reply!
I don't think that this has happened since your fix, but the bug was always difficult to produce. 
Would save us some merge-work if you would add it to the dev branch (since every time we update to the newest commit on develop we have to assess the changes and how they affect your fix), but I also understand if my "confirmation" above is to vague for you to trust it.

**Comment by krisgry** [comment]
BTW @paulosousadias  How does the above fix compare to commit https://github.com/LSTS/neptus/commit/dec1c22d070dab1ac0bdca375367f6835225482a (which is more recent)?

**Comment by paulosousadias** [comment]
Hi, I needed to check better, but you are right. This commit (dec1c22) might have resolved. I now remember that on 2020 I was able to track it down. It was a hard to fix issue. I would bet that you can try to merge just the develop without that branch that I made for you at that time.
If no issue from you in like 6 months tell me so I can delete the not merged branch.
